# Generated by Django 2.0.7 on 2018-07-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='account',
            field=models.CharField(choices=[('glader', 'Glader'), ('skyslayer', 'Skyslayer')], max_length=50, verbose_name='Аккаунт'),
        ),
    ]
