version: '3'
services:
  backend:
    build: .
    image: gladerru_backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    env_file: docker.env
    depends_on:
      - postgres
    volumes:
      - media:/app/media
    ports:
      - 8000:8000

  cron:
    build:
      context: .
      dockerfile: cron/Dockerfile
    image: gladerru_cron:latest
    env_file: docker.env
    depends_on:
      - postgres
    volumes:
      - media:/app/media

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: gladerru_nginx:latest
    env_file: docker.env
    depends_on:
      - backend
    volumes:
      - media:/app/media
    ports:
      - 80:80

  postgres:
    image: postgres:9.6
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  media:
