#!/bin/sh

GUNICORN=/home/www/projects/gladerru/ENV/bin/gunicorn
ROOT=/home/www/projects/gladerru/src
PID=/home/www/projects/gladerru/pid

APP=main:application

if [ -f $PID ]; then rm $PID; fi

echo $(date) restarted >> /var/log/projects/gladerru/restart.log

cd $ROOT
exec $GUNICORN -b unix:/home/www/projects/gladerru/fcgi.sock --pid=$PID $APP
