#!/bin/sh

echo $(date) restarted >> /var/log/projects/gladerru/restart.log
exec chpst -u www /home/www/projects/gladerru/ENV/bin/python /home/www/projects/gladerru/src/manage.py runfcgi errlog=/var/log/projects/gladerru/fcgi-error.log method=prefork host=127.0.0.1 port=3030 pidfile=/home/www/projects/gladerru/pid daemonize=false stdout=/var/log/projects/gladerru/stdout.log
