#!/bin/sh

echo $(date) restarted >> /var/log/projects/gladerru/restart-celery.log
exec chpst -u www cd /home/www/projects/gladerru/src & ../ENV/bin/python manage.py celeryd --settings=settings >> /var/log/projects/gladerru/celery.log
