# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('template', models.CharField(blank=True, default='', max_length=100, verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'LP',
                'verbose_name_plural': 'LP',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', jsonfield.fields.JSONField(default={}, verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b')),
                ('hash', models.CharField(max_length=100, verbose_name='\u0425\u044d\u0448')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432')),
                ('actions', models.PositiveIntegerField(default=0, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0439')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpages.LandingPage', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430',
            },
        ),
    ]
