# Generated by Django 2.0.7 on 2018-07-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landingpages.LandingPage', verbose_name='Страница'),
        ),
    ]
