# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 01:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_position'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
    ]
