# Generated by Django 2.0.7 on 2018-07-22 20:36

from django.db import migrations, models
import yafotki.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20151230_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='local_url',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='type',
            field=models.CharField(choices=[('auto', 'Из другой таблицы'), ('manual', 'Руками')], default='manual', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='local_url',
            field=models.CharField(default='', max_length=70, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('pub', 'Опубликовано'), ('save', 'Черновик'), ('deferred', 'Отложено'), ('del', 'Удалено'), ('ban', 'Забанено'), ('premoderate', 'Премодерация')], default='pub', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=yafotki.fields.YFField(blank=True, default=None, max_length=255, null=True, upload_to='gladerru', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pub', 'Опубликовано'), ('save', 'Черновик'), ('deferred', 'Отложено'), ('del', 'Удалено'), ('ban', 'Забанено'), ('premoderate', 'Премодерация')], default='save', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Пост'), ('page', 'Статическая страница')], default='post', max_length=15, verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Мальчик'), ('f', 'Девочка'), ('', 'Не определилось')], default='', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=yafotki.fields.YFField(blank=True, default=None, max_length=255, null=True, upload_to='gladerru', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.TextField(default='', verbose_name='Посты'),
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(choices=[('common', 'Общий словарь'), ('jib', 'Джиббинг'), ('preparatory', 'Подготовительные'), ('grabs', 'Гребы'), ('spins', 'Вращения'), ('bigspins', 'Продвинутые трюки'), ('jibbing_tricks', 'Джиббинг'), ('pipe_tricks', 'Пайповые прыжки'), ('other_tricks', 'Разное')], default='common', max_length=20, verbose_name='Словарь'),
        ),
    ]
