# Generated by Django 2.0.7 on 2018-07-22 20:36

from django.db import migrations, models
import yafotki.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='gender',
            field=models.CharField(choices=[('m', 'Мальчик'), ('f', 'Девочка')], default='m', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='man',
            name='image',
            field=yafotki.fields.YFField(blank=True, default=None, max_length=255, null=True, upload_to='gladerru', verbose_name='Портрет'),
        ),
        migrations.AlterField(
            model_name='man2movie',
            name='role',
            field=models.CharField(choices=[('actor', 'Райдер'), ('director', 'Режиссер')], default='actor', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=yafotki.fields.YFField(blank=True, default=None, max_length=255, null=True, upload_to='gladerru', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data/mp3', verbose_name='Файл'),
        ),
    ]
